name: LunaChatMC
version: '${project.version}'
main: dev.arcticgaming.lunachatmc.LunaChatMC
api-version: 1.19
authors: [ ArcticDev ]
depend: [ PlaceholderAPI ]
description: A fancy Chat Plugin
commands:
  message:
    description: sends a message
    aliases:
      - dm
      - msg
      - tell
  reply:
    description: reply to a message
    aliases: r